### ISSUE TITLE
Ubuntu 14.10 Utopic manual switching not working

### ISSUE THREAD

**Issue by heihachi88** [mildmojo/caffeine-plus#2]
When i press "Toggle Screensaver" in a system tray - nothing happens.

Kernel 3.18.1
VideoDriver Mesa 10.5 dev

**Comment by mildmojo** [comment]
When you click "Toggle Screensaver", you should see the hollow cup icon change to a solid cup with lines above it. That means it's engaged and it's telling the system there's user activity so it won't trigger the screensaver. It can be hard to see the lines.

Inactive
![Icon](https://github.com/mildmojo/caffeine-plus/blob/master/share/icons/ubuntu-mono-dark/status/48/caffeine-cup-empty.png?raw=true)

Active
![Icon](https://github.com/mildmojo/caffeine-plus/blob/master/share/icons/ubuntu-mono-dark/status/48/caffeine-cup-full.png?raw=true)

Is the icon changing? And does the screensaver still activate?

**Comment by heihachi88** [comment]
Yes, i saw them when i was on 13.6 kernel, but now i if i switch to active state i can't switch back to inactive. I can turn it off only by pressing quiet then restarting the app.

**Comment by mildmojo** [comment]
Huh. I set it up on a 14.10 VM, and I can duplicate the bug. It looks like the DBus Screensaver resource stops responding after the call to `Inhibit()`. Calling `UnInhibit()` on the second click never gets a DBus reply:

```
Traceback (most recent call last):
  File "./caffeine-plus", line 76, in on_toggle
    self._check_for_fullscreen();
  File "./caffeine-plus", line 122, in _check_for_fullscreen
    self.iface.UnInhibit(self.screenSaverCookie)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
```

I know very little about DBus, so I'm not sure why this is happening.

**Comment by mildmojo** [comment]
Okay, this looks like a known bug ([#1388759](https://bugs.launchpad.net/ubuntu/+source/unity-settings-daemon/+bug/1388759)) in Ubuntu 14.10 (Utopic). Sorry about that; Caffeine should start working again when Ubuntu fixes the bug. You might want to go click the green "This bug affects 3 people. Does it affect you?" link at the top of the Launchpad bug page to get notified when it's fixed:

[#1388759 powersaving/screensaver UnInhibit method times out over DBus](https://bugs.launchpad.net/ubuntu/+source/unity-settings-daemon/+bug/1388759)

**Comment by mildmojo** [comment]
Here's a ray of hope. The upstream project, Caffeine, switched to calling the `xdg-screensaver` command instead of communicating with the screensaver service over DBus. I can probably integrate [that change](http://bazaar.launchpad.net/~caffeine-developers/caffeine/main/revision/601) here.

**Comment by heihachi88** [comment]
Thanks for your effort. Where can i get an updated version?

Also. who's responsible for this: http://ppa.launchpad.net/nilarimogard/webupd8/ubuntu/pool/main/c/caffeine-plus/ ?

**Comment by mildmojo** [comment]
The original project, Caffeine, is [hosted on Launchpad](https://launchpad.net/caffeine). This fork was a reaction to the removal of the system tray icon and manual toggle (my personal use case). The original author has since [made plans] to add a companion tray indicator that restores the manual toggle behavior. When that happens, this project will be obsolete.

That PPA and package was created independently by [Andrew at WebUpd8](http://www.webupd8.org/2014/08/screensaver-lock-screen-inhibitor.html) based on this repo (which is awesome). If I can implement a fix, I guess he'll need to be notified to update his package.

**Comment by mildmojo** [comment]
I've switched the toggle mechanism to use `xdg-screensaver` like the original project, so it should now work in Ubuntu 14.10 and derivatives. Tested in Xubuntu 14.10.
