### ISSUE TITLE
Manual switching not working

### ISSUE THREAD

**Issue by brbsix** [mildmojo/caffeine-plus#4]
This bug report is similar to "Ubuntu 14.10 Utopic manual switching not working #2". I am using Xubuntu 14.04 but this does not appear to be distro, evironment, or kernel specific. The steaming coffee icon was not being displayed and I was getting DBUS exceptions on the terminal. DBUS was calling `org.freedesktop.ScreenSaver` which doesn't exist and appears to be deprecated in favor of `org.freedesktop.PowerManagement.Inhibit`.

Using the patch @ https://bazaar.launchpad.net/~caffeine-developers/caffeine/main/revision/601 fixed the problem.

If you don't want to use xdg-screensaver, you can use this instead:

    try:
        self.susuProxy = bus.get_object('org.freedesktop.ScreenSaver', '/org/freedesktop/ScreenSaver')
        self.iface = dbus.Interface(self.susuProxy, 'org.freedesktop.ScreenSaver')
    except:
        self.susuProxy = bus.get_object('org.freedesktop.PowerManagement', '/org/freedesktop/PowerManagement/Inhibit')
        self.iface = dbus.Interface(self.susuProxy, 'org.freedesktop.PowerManagement.Inhibit')

I encountered this problem using the nilarmogard webupd8 caffeine-plus but since you're upstream, you may want to incorporate the change.

The official version of caffeine recently released v2.8.3 which includes caffeine-indcator so all this may be for naught. Just an FYI, I checked the source for v2.8.3 and they are using a solution very similar to https://bazaar.launchpad.net/~caffeine-developers/caffeine/main/revision/601 except xdg-screensaver has been patched up and renamed caffeine-screensaver.

**Comment by mildmojo** [comment]
Thanks for the detailed writeup and the note about the new version of caffeine. If the original now has an indicator, I'll probably deprecate this fork since that was the whole reason for it in the first place.

Interesting that it's throwing a fit on Xubuntu. Linux Mint 17, 17.1, and Ubuntu 14.04 have been working for me. I'll see about integrating the patch you linked from the original project until I can get back around to trying installing it again.

**Comment by mildmojo** [comment]
I've switched the toggle mechanism to use `xdg-screensaver` like the original project, so it should now work in Ubuntu 14.10 and derivatives. Tested in Xubuntu 14.10.
