### ISSUE TITLE
Does not work after back from suspend.

### ISSUE THREAD

**Issue by xkill** [mildmojo/caffeine-plus#7]
After suspend the computer with caffeine enabled, it stopped working and the screensaver was not disabled by caffeine.

**Comment by mildmojo** [comment]
Hi! I'm really sorry, I've been dragging my heels about deprecating this project. The upstream [caffeine project](https://launchpad.net/caffeine) added a `caffeine-indicator` applet to restore the system tray icon for controlling caffeine. This happened a long time ago.

Again, I apologize, but please try the upstream [caffeine](https://launchpad.net/caffeine) project instead. This one is deprecated and is no longer maintained. I think the upstream will do the trick for you.
